name: CI - Biblioteca Pessoal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build and run tests
        run: mvn -B verify

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ghcr.io/halissonfranca/deveops-2:${{ github.sha }}




  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: docker
    environment: development
    steps:
      - name: Simulate deploy to development
        run: |
          echo "Deploying image to development:"
          echo "ghcr.io/${{ github.repository_owner }}/biblioteca-pessoal:${{ github.sha }}"
          # aqui você faria os passos reais (kubectl, ssh, docker pull, etc)

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production
    steps:
      - name: Simulate deploy to production
        run: |
          echo "Approved — deploying to production..."
          echo "ghcr.io/${{ github.repository_owner }}/biblioteca-pessoal:${{ github.sha }}"
